# Import Librairies 


In [44]:

import torch.nn as nn
import torch
import torch.nn.functional as F
import math,copy,re
import warnings
import pandas as pd
import numpy as np
from torch.autograd import Variable


## Create Word Embdding

In [ ]:
class Embedding (nn.Module):
    def __init__(self, vocab_size, embedding_dim):
        """
        Args:
            vocab_size: size of the vocabulary. 
            embedding_dim: size of the word embedding
        """
        super(Embedding, self).__init__()
        self.vocab_size = vocab_size
        self.embedding_dim = embedding_dim
        self.embeddings = nn.Embedding(self.vocab_size, self.embedding_dim)
        
    def forward(self, x):
        """
        Args:
            x: input vector
        Returns:        
            out: embedded vector
        """
        return self.embeddings(x)
    



    


## Positional Encoding


In [ ]:
class PositionalEncoding(nn.Module):
    def __init__(self, d_model, dropout=0.1, max_seq_len=5000):
        super(PositionalEncoding, self).__init__()
        pe = torch.zeros(max_seq_len, d_model)
        for pos in range(max_seq_len):
            for i in range(0, d_model, 2):
                pe[pos,i]= math.sin(pos/10000**(i/d_model))
                pe[pos,i+1]=math.cos(pos/10000**(i/d_model))
        pe = pe.unsqueeze(0)
        self.register_buffer('pe', pe)
        
        def forward(self, x):
            # x has dimensions (batch_size, seq_len, d_model)
            
            # Scale embeddings by the square root of d_model
            x = x * math.sqrt(self.d_model)
            
            # Get the sequence length from the input tensor
            seq_len = x.size(1)
            
            # Add positional encoding to the input tensor
            x = x + torch.autograd.Variable(self.pe[:, :seq_len], requires_grad=False)
    
            return x


        


Tensor 3D original:
[[[ 1.8030983  -1.1595311   1.1304315  -0.10533942]
  [ 1.0083343   0.47773212 -0.141545    0.6026402 ]
  [ 0.23053083  1.3774903  -1.5789098  -0.61902785]]

 [[-0.05004444  0.28028554 -0.06326415  0.3739637 ]
  [-0.5093646  -0.6148853  -0.6047851   2.1334984 ]
  [-0.19640008  0.6885371   0.94157475  1.247575  ]]]

1ère matrice (indice 0):
[[ 1.8030983  -1.1595311   1.1304315  -0.10533942]
 [ 1.0083343   0.47773212 -0.141545    0.6026402 ]
 [ 0.23053083  1.3774903  -1.5789098  -0.61902785]]

2ème ligne de la 2ème matrice (indice 1):
[-0.5093646 -0.6148853 -0.6047851  2.1334984]

Élément à l'indice [1, 2, 3]:
1.247575
[[ 0.23053083  1.3774903  -1.5789098  -0.61902785]
 [-0.19640008  0.6885371   0.94157475  1.247575  ]]


In [30]:
# Create a tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor= tensor.unsqueeze(0)
# Print the tensor
print(tensor.cpu().numpy())
print(tensor.shape)


[[[1 2 3]
  [4 5 6]]]
torch.Size([1, 2, 3])


In [19]:
import torch

tensor = torch.tensor([[[1, 2, 3]]])  # Shape: (1, 1, 3)
print("Original tensor shape:", tensor.shape)

squeezed_tensor = tensor.squeeze()
print("Squeezed tensor shape:", squeezed_tensor.shape)



Original tensor shape: torch.Size([1, 1, 3])
Squeezed tensor shape: torch.Size([3])


In [20]:
tensor = torch.tensor([1, 2, 3])  # Shape: (3,)
print("Original tensor shape:", tensor.shape)

unsqueezed_tensor = tensor.unsqueeze(0)  # Adds a dimension at the beginning
print("Unsqueezed tensor shape:", unsqueezed_tensor.shape)


Original tensor shape: torch.Size([3])
Unsqueezed tensor shape: torch.Size([1, 3])
